[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-UK"
    footer = '© 1999-2025, <a href="https://netribution.org">Netribution Ltd</a>'
